### PR TITLE
Ajm products

### PR DESCRIPTION
**Pull request by amillion3**
Products should have full CRUD functionality. No checks are built in, so if you enter invalid data (say, an `owner_id` that doesn't match), it will probably just break.

### CODE REVIEW

**Comment by BLRussell-09** [comment]
Having a little trouble with the delete function. Given your notes I assume it's something I'm missing with the owner_id, but everything else works well

**Comment by amillion3** [comment]
What kind of error or troubles with delete, are you having? I'll dig into it tonight.

**Comment by BLRussell-09** [comment]
Hell yeah! Looks great 👍

**Comment by AlexOrga** [comment]
looking good my dood!

**Pull request merged**
