### PR TITLE
Br search customers

### PR DESCRIPTION
**Pull request by BLRussell-09**

### CODE REVIEW

**Comment by amillion3** [comment]
Slick! 👍

**Comment by BLRussell-09** [comment]
Hey Andy, did you have issues with the single customers with this branch? I wasn't able to reproduce those errors, but I wonder if they got fixed somewhere in the mix

**Comment by amillion3** [comment]
I did still have those issues happening on my end. Not sure why, perhaps I should restart my machine...

**Comment by AlexOrga** [comment]
👍 sweeeeet

**Pull request merged**
