### PR TITLE
Br get emps

### PR DESCRIPTION
**Pull request by BLRussell-09**

### CODE REVIEW

**Comment by amillion3** [comment]
I think adding an alert/notification of some kind would be good after you successfully update the employee. 
Checkbox or dropdown for true/false? :-D

**Comment by amillion3** [comment]
@BLRussell-09 Sorry Barry, still seeing one issue. If I edit an employee, I am forced to update the 'is supervisor' status every time. Everything else seems fine though.

image

**Comment by BLRussell-09** [comment]
Got Checkboxes now!!!

**Comment by AlexOrga** [comment]
👍

**Comment by amillion3** [comment]
Please don't hate me Barry. When I update a record, it seems all the department Ids come up as 0 for me. Does that happen to anyone else? @AlexOrga 
image

**Comment by amillion3** [comment]
👍

**Pull request merged**
