### PR TITLE
Br single customer rest

### PR DESCRIPTION
**Pull request by BLRussell-09**

### CODE REVIEW

**Comment by amillion3** [comment]
Looks good! I was able to view a single customer and add a customer without issue.

Do you want to display the `active` status on the single customer page?

Getting a couple small errors, but I think they should be quick fixes:
image

**Comment by BLRussell-09** [comment]
Yeah it looks like those errors are due to the navbar. As far as the active bit goes I can add that to the page, working on getting the updates done rn.

**Comment by AlexOrga** [comment]
Ditto to everything Andy said.

**Comment by BLRussell-09** [comment]
gonna merge, fixed that bug in my latest pr

**Pull request merged**
