### PR TITLE
Br customer validation

### PR DESCRIPTION
**Pull request by BLRussell-09**

### CODE REVIEW

**Comment by amillion3** [comment]
👍 Code looks great.

In the `CustomerModel.cs`, you can also validate the types of incoming data, IE, strings:
`[DataType(DataType.Text)]`

Do you know how to be more specific with error messages on the backend side? I don't know, but I'm hoping you do .
`return BadRequest();`

**Comment by BLRussell-09** [comment]
You can put string messages in them amigo. https://docs.microsoft.com/en-us/dotnet/api/system.web.http.apicontroller.badrequest?view=aspnetcore-2.1#System_Web_Http_ApiController_BadRequest_System_String_

**Comment by amillion3** [comment]
I think I did a poor job at wording my comment. My intent was to let you know about another way to validate input. If you only wanted an email address or date or credit card, etc. You can use the `[DataType(DataType.XYZ)]`

Nathan didn't mention it, but I stumbled across it and it seems like it could be useful in certain cases.

[Docs](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.datatype?view=netframework-4.7.2)

**Comment by BLRussell-09** [comment]
Oh yeah, I got what you were saying on validation. But I thought you were also asking for a way to be more specific with the BadRequest() method. You can put string messages inside them as well.

**Pull request merged**
